# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/raulett/store_vol/YandexDisk/Work/ProjectsRepositories/20210416_Rousettus/RousettusTool/UI/Settings/AppSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppSettingsDialog(object):
    def setupUi(self, AppSettingsDialog):
        AppSettingsDialog.setObjectName("AppSettingsDialog")
        AppSettingsDialog.resize(476, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AppSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.debug_checkBox = QtWidgets.QCheckBox(AppSettingsDialog)
        self.debug_checkBox.setMinimumSize(QtCore.QSize(120, 0))
        self.debug_checkBox.setObjectName("debug_checkBox")
        self.verticalLayout.addWidget(self.debug_checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(AppSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AppSettingsDialog)
        self.buttonBox.accepted.connect(AppSettingsDialog.accept)
        self.buttonBox.rejected.connect(AppSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AppSettingsDialog)

    def retranslateUi(self, AppSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        AppSettingsDialog.setWindowTitle(_translate("AppSettingsDialog", "Dialog"))
        self.debug_checkBox.setText(_translate("AppSettingsDialog", "Debug mode"))
