# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/raulett/store_vol/YandexDisk/Work/ProjectsRepositories/20210416_Rousettus/RousettusTool/UI/FlightPlanning/flight_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreviewWindow(object):
    def setupUi(self, PreviewWindow):
        PreviewWindow.setObjectName("PreviewWindow")
        PreviewWindow.resize(1372, 453)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PreviewWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.flights_tableview = QtWidgets.QTableView(PreviewWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flights_tableview.sizePolicy().hasHeightForWidth())
        self.flights_tableview.setSizePolicy(sizePolicy)
        self.flights_tableview.setObjectName("flights_tableview")
        self.flights_tableview.horizontalHeader().setCascadingSectionResizes(True)
        self.flights_tableview.horizontalHeader().setMinimumSectionSize(20)
        self.horizontalLayout.addWidget(self.flights_tableview)

        self.retranslateUi(PreviewWindow)
        QtCore.QMetaObject.connectSlotsByName(PreviewWindow)

    def retranslateUi(self, PreviewWindow):
        _translate = QtCore.QCoreApplication.translate
        PreviewWindow.setWindowTitle(_translate("PreviewWindow", "Flight preview"))
