# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\YandexDisk\Work\ProjectsRepositories\20210416_VKR_Project\RousettusTool\UI\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 719)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        self.logTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logTextEdit.sizePolicy().hasHeightForWidth())
        self.logTextEdit.setSizePolicy(sizePolicy)
        self.logTextEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.logTextEdit.setMaximumSize(QtCore.QSize(16777215, 200))
        self.logTextEdit.setUndoRedoEnabled(True)
        self.logTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout.addWidget(self.logTextEdit)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 31))
        self.menubar.setObjectName("menubar")
        self.data_processing_menu = QtWidgets.QMenu(self.menubar)
        self.data_processing_menu.setEnabled(False)
        self.data_processing_menu.setObjectName("data_processing_menu")
        self.menuMagnetic_Data = QtWidgets.QMenu(self.data_processing_menu)
        self.menuMagnetic_Data.setEnabled(False)
        self.menuMagnetic_Data.setObjectName("menuMagnetic_Data")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.exitButton = QtWidgets.QAction(MainWindow)
        self.exitButton.setObjectName("exitButton")
        self.DBsettingsButton = QtWidgets.QAction(MainWindow)
        self.DBsettingsButton.setObjectName("DBsettingsButton")
        self.action_CSV = QtWidgets.QAction(MainWindow)
        self.action_CSV.setObjectName("action_CSV")
        self.OpenPrjButton = QtWidgets.QAction(MainWindow)
        self.OpenPrjButton.setObjectName("OpenPrjButton")
        self.actionVariation_calculate = QtWidgets.QAction(MainWindow)
        self.actionVariation_calculate.setEnabled(False)
        self.actionVariation_calculate.setObjectName("actionVariation_calculate")
        self.menuMagnetic_Data.addAction(self.actionVariation_calculate)
        self.data_processing_menu.addAction(self.menuMagnetic_Data.menuAction())
        self.menu_2.addAction(self.OpenPrjButton)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.exitButton)
        self.menu_3.addAction(self.DBsettingsButton)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.data_processing_menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RousettusTool"))
        self.data_processing_menu.setTitle(_translate("MainWindow", "Data Processing"))
        self.menuMagnetic_Data.setTitle(_translate("MainWindow", "Magnetic Data"))
        self.menu_2.setTitle(_translate("MainWindow", "Файл"))
        self.menu_3.setTitle(_translate("MainWindow", "Параметры"))
        self.exitButton.setText(_translate("MainWindow", "Выйти"))
        self.DBsettingsButton.setText(_translate("MainWindow", "Параметры БД"))
        self.action_CSV.setText(_translate("MainWindow", "из файла CSV"))
        self.OpenPrjButton.setText(_translate("MainWindow", "Открыть проект"))
        self.actionVariation_calculate.setText(_translate("MainWindow", "Variation calculate"))

